# Generated by Django 5.0.14 on 2026-09-22 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tagline', models.CharField(blank=True, default='Contemporary Minimalist Fashion', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('currency_symbol', models.CharField(default='EGP', max_length=10)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, default='concierge@noire.studio', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='+20 100 000 0000', max_length=50)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tiktok_url', models.URLField(blank=True, max_length=500, null=True)),
                ('announcement_bar_text', models.CharField(blank=True, default='COMPLIMENTARY DOMESTIC SHIPPING ON ORDERS OVER EGP 1,500', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
